SetRandomSeed(1, 2)

local names = {
  "$action_mystery_secret_spell",
  "$action_mystery_silent_spell",
  "$action_mystery_ancient_spell",
  "$action_mystery_raging_spell",
  "$action_mystery_mystic_spell",
  "$action_mystery_abyssal_spell",
  "$action_mystery_obsidian_spell",
  "$action_mystery_screaming_spell",
  "$action_mystery_azure_flame_spell",
  "$action_mystery_enchanting_spell",
  "$action_mystery_cruel_spell",
  "$action_mystery_shining_spell",
  "$action_mystery_stardust_spell",
  "$action_mystery_cerulean_spell",
  "$action_mystery_forbidden_spell",
  "$action_mystery_dark_spell",
  "$action_mystery_shadowy_soul_spell",
  "$action_mystery_insanity_spell",
  "$action_mystery_odd_spell",
  "$action_mystery_malicious_spell",
  "$action_mystery_melancholic_spell",
  "$action_mystery_mysterious_spell",
  "$action_mystery_eerie_spell",
  "$action_mystery_disillusionment_spell",
  "$action_mystery_nether_spell",
  "$action_mystery_thundering_spell",
  "$action_mystery_eternal_spell",
  "$action_mystery_forgetful_spell",
  "$action_mystery_serpentine_spell",
  "$action_mystery_hatred_spell",
  "$action_mystery_dark_cloud_spell",
  "$action_mystery_abominable_spell",
  "$action_mystery_void_spell",
  "$action_mystery_treachery_spell",
  "$action_mystery_lost_spell",
  "$action_mystery_invisible_spell",
  "$action_mystery_ruination_spell",
  "$action_mystery_underworld_spell",
  "$action_mystery_deceptive_spell",
  "$action_mystery_hazy_spell",
  "$action_mystery_enigmatic_spell",
  "$action_mystery_crawling_spell",
  "$action_mystery_rebellious_spell",
  "$action_mystery_obscure_spell",
  "$action_mystery_chaotic_spell",
  "$action_mystery_nostalgic_spell",
  "$action_mystery_phantom_spell",
  "$action_mystery_ensnaring_spell",
  "$action_mystery_sly_spell",
  "$action_mystery_cold_blooded_spell",
  "$action_mystery_fateful_spell",
  "$action_mystery_fallen_spell",
  "$action_mystery_creepy_spell",
  "$action_mystery_demonic_spell",
  "$action_mystery_terrifying_spell",
  "$action_mystery_rupturing_spell",
  "$action_mystery_everlasting_spell",
  "$action_mystery_confining_spell",
  "$action_mystery_empty_spell",
  "$action_mystery_soulful_cry_spell",
  "$action_mystery_malicious_shadow_spell",
  "$action_mystery_sorrowful_spell",
  "$action_mystery_dark_magic_spell",
  "$action_mystery_phantasmal_spell",
  "$action_mystery_spell_of_oblivion",
  "$action_mystery_fictitious_spell",
  "$action_mystery_favorite_spell",
  "$action_mystery_decayed_wish_spell",
  "$action_mystery_well_worn_spell",
  "$action_mystery_new_spell",
  "$action_mystery_suspicious_spell" }

local function get()
  return names[Random(0, #names)]
end

return {
  get = get,
}
